Add `ant_class` module for classifying antennas based on absolute bounds for various metrics
HERA-Team/hera_qm pull request #419
Opened 2022-07-29 00:54 UTC by jsdillon

This PR adds a new module `ant_class` and the `AntennaClassification` object, which allows for the flexible categorization of ant-pol tuples. 

It is initialized like `AntennaClassification(good=[(0, 'Jee'), (1, 'Jee')], whatever=[(0, 'Jnn'), (10, 'Jee')])` and takes arbitrary categorizations. Allows setting and getting of a specific antenna's classification using `[]`, as well as `.ants` and `.classes` properties and a `.get_all(classification)` function.

However, there are three special "quality" classifications (by default `"good"`, `"suspect"`, and `"bad"`, but they can be modified) that are queried via the property e.g. `.good_ants` or the function `.is_good(ant).` Furthermore, these classifications the sensible enable combination of `AntennaClassification` objects by overloading `+` such that good + good = good, good + bad = bad, good + suspect = suspect, bad + suspect = bad, and bad + bad = bad.

This PR adds also a new function `antenna_bounds_checker()` to `ant_class` designed for turning scalar antenna metrics into `AntennaClassification` objects. This function is very general and I plan to add absolute limits checkers built on top of it.

This PR lays the groundwork for future absolute limits checking. Eventually, the goal here is to implement new absolute limit checking on antenna power, bandpass slope, etc. as has been prototyped in https://github.com/HERA-Team/hera_notebook_templates/blob/ef53071cfac322a6fe9d629d0ed508028bd1fe3c/notebooks/fastcal_inspect.ipynb

2022-07-29 19:41 UTC, tyler-a-cox commented on hera_qm/ant_class.py
> +    '''Verifies that input is a valid ant-pol tuple. Otherwies, raises a ValueError'''
Minor typo here "Otherwies"

2022-07-29 19:42 UTC, tyler-a-cox requested changes
Looks good to me! I find a minor typo in one of the doc strings, but besides that I think this is really clear. Happy to approve after typo gets fixed

2022-07-29 21:26 UTC, jsdillon commented
Ok, fixed. Thanks @tyler-a-cox!

2022-08-01 17:57 UTC, tyler-a-cox approved these changes
Looks good! Thanks @jsdillon

2022-08-01 18:00 UTC, merged